modLoader = "javafml"
loaderVersion = "*"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
authors = "PigCart"
description = '''
${description}
'''

[[dependencies.dedicatedmcupnp]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dedicatedmcupnp]]
modId = "minecraft"
mandatory = true
versionRange = "[${lowest_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dedicatedmcupnp]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"