modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''${mod_description}'''
authors = "${mod_author}"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
ordering = "NONE"
side = "SERVER"


[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange="${version_range}"

[mc-publish]
loaders=["${forge_or_neoforge}"]
version="${mod_version}"