modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/PigCart/dedicatedmcupnp/issues"
license = "MIT"

[[mods]]
modId = "dedicatedmcupnp"
version = "${version}"
authors = "PigCart"
description = '''
Opens ports when the server starts and closes them when it stops
'''

[[dependencies.dedicatedmcupnp]]
modId = "neoforge"
type = "required"
versionRange = "[${neoForgeVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dedicatedmcupnp]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dedicatedmcupnp]]
modId = "architectury"
type = "required"
versionRange = "[${architecturyVersion},)"
ordering = "AFTER"
side = "BOTH"