modLoader = "javafml"
loaderVersion = "*"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
authors = "PigCart"
description = '''
${description}
'''

[[dependencies.dedicatedmcupnp]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dedicatedmcupnp]]
modId = "minecraft"
type = "required"
versionRange = "[${lowest_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dedicatedmcupnp]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"